auto: true
markdown: rdiscount
pygments: true

title: Maulik Suchak Blog

url: http://www.ermauliks.github.io

permalink: /:year/:month/:day/:title/

author:
    name: Maulik Suchak
    email: suchak.maulik179@gmail.com
    github: ermauliks
    twitter: ermauliks
    gravatar: http://www.gravatar.com/avatar/821fb744f4b620bccd70ecfddeb8c7c4.png

comments:
    provider: disqus
    disqus:
        short_name: ermauliksgithubio
        
analytics:
    provider: google 
    google: 
        tracking_id: 'UA-40337186-2'
        domain: 'ermauliks.github.io'